fix(operator): add clientScopes, requiredActions to the realm reconciliation
VibrentHealth/keycloak-operator pull request #33
Opened 2022-11-11 20:40 UTC by georgiydeliya

AC-123390

2022-11-15 15:18 UTC, stephen-yates approved these changes
LGTM

2022-11-15 20:24 UTC, Michael-Valeiras requested changes

2022-11-15 20:24 UTC, Michael-Valeiras commented on README.md
> +* New logic for updating "realm clientScopes" and "realm requiredActions" in the KeycloakRealm reconcile logic.
Please update chart version to `1.8.0`, and create a new sub-section for this line item. While there is no direct reason to update the helm chart version when making application updates, most of our CI pipelines rely on setting a specific `appVersion` when compiling and uploading the chart artifact. I believe rebuilding the chart with the same version will led to the new code potentially being deployed early to unexpected environments (since helm updates are applied on non-related cluster-management updates).

This is something we can follow up on in the future, but for now I'd like to continue double-using the helm version as the "feature" version, and updating the second number (`7 -> 8`) for each release.

2022-11-15 20:24 UTC, Michael-Valeiras commented on pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
> +type KeycloakAPIRequiredAction struct {
This change is just to fix a typo from the upstream? I see the corresponding automated change - no need for CRD change?

Follow up question: there were no existing references to this `struct` already existing in the code that also needs a matching update?

2022-11-15 20:24 UTC, Michael-Valeiras commented on pkg/common/cluster_actions.go
> +	if len(requiredActionsToAdd) > 0 {
This was required for roles, specifically to support composites: The use case where a single change contains a new role AND adds that new role to another role as a composite.

Is there any scenario where the newly created role needs to be referenced again? You pass the rebuilt map into `compareAndUpdateRealmRequiredAction`, but do you need to or use it?

Same question for clientScope implementation.

2022-11-16 14:20 UTC, georgiydeliya commented on pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
> +type KeycloakAPIRequiredAction struct {
it's not even typo, it just makes more sense to use an array of KeycloakAPIRequiredAction
`RequiredActions []KeycloakAPIRequiredAction `json:"requiredActions,omitempty"` 
CRD has RequiredActions, so that won't require any change, and no it wasn't used anywhere else actually

2022-11-16 16:01 UTC, Michael-Valeiras commented on pkg/common/cluster_actions.go
>  		err = i.compareAndUpdateRealmClientScope(realmName, desiredRealmClientScopeMap[name], actualRealmClientScopeMap[name], actualRealmClientScopeMap, actionLogger)
You should remove the `actualRealmClientScopeMap` argument from this function and the one for required actions, as they are not used in the function implementations (same reason you don't need to rebuild the mapping after adding a  new one).

2022-11-18 17:41 UTC, Michael-Valeiras approved these changes
LGTM

2022-11-18 17:42 UTC, merged